namespace Numarataj.WebUI.Helpers
{
    public static class Constants
    {
        public static readonly List<string> Mahalleler = new List<string>
        {
            "19 MAYIS MAHALLESİ", "AKYÜREK MAHALLESİ", "AYDINLIKEVLER MAHALLESİ", "BAĞLAR MAHALLESİ",
            "BAHÇELİEVLER MAHALLESİ", "BAYINDIR MAHALLESİ", "BELDE MAHALLESİ", "BEŞEVLER MAHALLESİ", "CUDİ MAHALLESİ",
            "CUMHURİYET MAHALLESİ", "ÇAMLICA MAHALLESİ", "ÇAMLITEPE MAHALLESİ", "ÇARŞI MAHALLESİ", "ÇAY MAHALLESİ",
            "FATİH MAHALLESİ", "GAP MAHALLESİ","GİRBEREŞİK MAHALLESİ", "GÜLTEPE MAHALLESİ", "GÜNEYKENT MAHALLESİ", "HİLAL MAHALLESİ",
            "HUZUR MAHALLESİ", "HÜRRİYET MAHALLESİ", "İLUH MAHALLESİ","İRMİ MAHALLESİ ", "KARŞIYAKA MAHALLESİ","KARDELEN MAHALLESİ", "KISMET MAHALLESİ", "KORİK MAHALLESİ",
            "KÜLTÜR MAHALLESİ", "MEYDAN MAHALLESİ", "PAZARYERİ MAHALLESİ", "PETROL MAHALLESİ", "PETROLKENT MAHALLESİ",
            "PINARBAŞI MAHALLESİ", "RAMAN MAHALLESİ", "SAĞLIK MAHALLESİ", "SEYİTLER MAHALLESİ","ŞAFAK MAHALLESİ",
            "ŞİRİNEVLER MAHALLESİ", "TİLMERC MAHALLESİ", "YENİ MAHALLESİ",
            "YENİŞEHİR MAHALLESİ", "YEŞİLTEPE MAHALLESİ", "ZİYAGÖKALP MAHALLESİ"
        };
    }
}
